create table if not exists public.personalization_profiles (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id),
  name varchar(80) not null,
  config_json text not null default '{}',
  created_at timestamp without time zone,
  updated_at timestamp without time zone
);

create unique index if not exists uq_personalization_profile_user_name
  on public.personalization_profiles (user_id, name);

create index if not exists ix_personalization_profiles_user_id
  on public.personalization_profiles (user_id);

create table if not exists public.communication_usage (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id),
  profile_id integer references public.personalization_profiles(id),
  phrase varchar(200) not null,
  usage_count integer not null default 0,
  last_used_at timestamp without time zone
);

create unique index if not exists uq_communication_usage_user_profile_phrase
  on public.communication_usage (user_id, profile_id, phrase);

create index if not exists ix_communication_usage_user_id
  on public.communication_usage (user_id);

create index if not exists ix_communication_usage_profile_id
  on public.communication_usage (profile_id);
